# Generated by Django 3.2.2 on 2021-05-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
